pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: Merge submodules automatically
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - label=dependabot-submodules
      - base=dev
    actions:
      merge:
        method: merge
  - name: Merge non-breaking dependencies automatically
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - title~=from (?P<major>\d+).\d+.\d+ to (?P=major).\d+.\d+
      - base=dev
    actions:
      merge:
        method: merge
  - name: Notify breaking dependencies automatically
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - title~=from (?P<major>\d+).\d+.\d+ to (?!(?P=major).\d+.\d+)
    actions:
      comment:
        message: |
          This PR features a major change and requires further approval.
      request_reviews:
        users:
          - Snazzah
          - Yamboy1
  - name: Notify bad bases in automatic PRs
    conditions:
      - author~=^dependabot(|-preview)\[bot\]$
      - base!=dev
    actions:
      comment:
        message: |
          This PR is not on the right branch.
      request_reviews:
        users:
          - Snazzah
          - Yamboy1

